<?php

/**
 * @file
 * Short file description here.
 *
 * Long description here.
 */

use CMRF\Drupal\Core;

require_once('vendor/autoload.php');


/**
 * global function to get the CMRF core
 */
static $_cmrf_core_singleton = NULL;
function cmrf_core_get_core() {
  global $_cmrf_core_singleton;
  if ($_cmrf_core_singleton===NULL) {
    include_once('CMRF_Drupal/Core.php');
    $_cmrf_core_singleton = new Core();
  }
  return $_cmrf_core_singleton;
}



/**
 * Implements hook_menu().
 */
function cmrf_core_menu() {
  $items['admin/config/civimrf'] = [
    'title' => 'CiviMRF',
    'description' => 'Edit connection profile settings for CiviMRF.',
    'page callback' => 'cmrf_core_admin',
    'position' => 'left',
    'weight' => 15,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
  ];
  $items['admin/config/civimrf/profiles'] = [
    'title' => 'CiviMRF Profiles',
    'description' => 'Edit connection profile settings for CiviMRF.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmrf_core_admin_form'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => ['administer cmrf'],
    'file' => 'cmrf_core.admin.inc',
  ];
  return $items;
}

/**
 * Implements hook_permission().
 */
function cmrf_core_permission() {
  return array(
    'administer cmrf' => array(
      'title' => t('Administer CiviMRF'),
    ),
  );
}
