<?php

if (!class_exists('\CMRF\PersistenceLayer\SQLPersistingCallFactory')) {
  require_once dirname(__FILE__) . '/vendor/autoload.php';
}

use Drupal\cmrf_core\SQLPersistingCallFactory;
use Drupal\cmrf_core\Entity\CMRFConnector;

function cmrf_core_schema() {
  $array=array();
  $array['civicrm_api_call'] = SQLPersistingCallFactory::schema();
  return $array;
}

/**
 * Add columns "entity" and "action" to the "civicrm_api_call" database table.
 */
function cmrf_core_update_8201(&$sandbox) {
  $entity_field = array(
    'description' => 'The CiviCRM API entity',
    'type' => 'varchar',
    'length' => 255,
    'not null' => TRUE,
    'default' => '',
  );
  \Drupal::database()->schema()->addField('civicrm_api_call', 'entity', $entity_field);

  $action_field = array(
    'description' => 'The CiviCRM API action',
    'type' => 'varchar',
    'length' => 255,
    'not null' => TRUE,
    'default' => '',
  );
  \Drupal::database()->schema()->addField('civicrm_api_call', 'action', $action_field);
}

/**
 * Updates empty connection type in connector configuration to remote
 */
function cmrf_core_update_8202() {
  $query   = \Drupal::entityQuery('cmrf_connector');
  $results = $query->execute();
  foreach($results as $result){
    $connector = CMRFConnector::load($result);
    if(empty($connector->connectiontype)){
      $connector->connectiontype='remote';
    };
    $connector->save();
  }
}
