cmrf_core.cmrf_credential.*:
  type: config_entity
  label: 'CMRF config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
