cmrf_core.cmrf_profile.*:
  type: config_entity
  label: 'CiviMRF Profile'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    url:
      type: string
      label: 'URL APIv3'
    urlV4:
      type: string
      label: 'URL APIv4'
    site_key:
      type: string
      label: 'Site key'
    api_key:
      type: string
      label: 'API key'
