cmrf_core.cmrf_credentials.*:
  type: config_entity
  label: 'CMRF config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    url:
      type: string
      label: 'URL'
    site_key:
      type: string
      label: 'Site key'
    api_key:
      type: string
      label: 'API key'
