cmrf_core.cmrf_profile.*:
  type: config_entity
  label: 'CiviMRF Profile'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    url:
      type: string
      label: 'URL'
    site_key:
      type: string
      label: 'Site key'
    api_key:
      type: string
      label: 'API key'
    cache_expire_days:
      type: integer
      label: 'Cache expire days'
