<?php

function cmrf_example_sendCall($entity, $action, $parameters, $options, $profile) {
  $connector_name = cmrf_example_get_connector_name($profile);
  $core = cmrf_core_get_core();
  $connector_id = variable_get($connector_name);
  if (empty($connector_id)) {
    $connector_id = $core->registerConnector($connector_name, $profile);
    variable_set($connector_name, $connector_id);
  }

  //$options['retry_count'] = 5;
  //$options['retry_interval'] = '1 second';

  $call = $core->createCall($connector_id, $entity, $action, $parameters, $options);
  $core->executeCall($call);
  return $call;
}

function cmrf_example_get_connector_name($profile) {
  return 'cmrf_example:'.$profile.':';
}

/**
 * Implements hook_menu().
 */
function cmrf_example_menu() {
  $items['admin/config/civimrf/examples'] = array(
    'title' => 'Example CiviMRF Calls',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmrf_example_form'),
    'access arguments' => array('cmrf access example'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function cmrf_example_permission() {
  return array(
    'cmrf access example' => array(
      'title' => t('Access CMRF example page'),
    ),
  );
}

function cmrf_example_form($form, &$form_state) {
  $profiles = cmrf_core_list_profiles();
  $profiles_options = array();
  foreach($profiles as $profile_name => $profile) {
    $profiles_options[$profile_name] = $profile['label'];
  }
  $form['profile']['#type'] = 'select';
  $form['profile']['#title'] = t('Select connection profile');
  $form['profile']['#options'] = $profiles_options;
  $form['profile']['#required'] = true;

  $form['actions']['#type'] = 'actions';
  $form['actions']['submit']['#type'] = 'submit';
  $form['actions']['submit']['#value'] = t('Test with this profile');
  $form['actions']['submit']['#ajax'] = array(
    'callback' => 'cmrf_example_form_ajax_submit',
    'wrapper' => 'cmrf-example-form',
    'method' => 'replace',
    'effect' => 'fade',
  );

  return $form;
}

function cmrf_example_form_ajax_submit($form, $form_state) {
  if (isset($form_state['values']['profile'])) {
    $call = cmrf_example_sendCall('Contact', 'getcount', [], [], $form_state['values']['profile']);
    $contact_count_reply = $call->getReply();
    $form['contact_count']['heading']['#markup'] = '<h2>' . t('Contact count') . '</h2>';
    $form['contact_count']['description']['#markup'] = '<p>' . t('Number of contacts in your CiviCRM installation') . '</p>';
    $form['contact_count']['content']['#markup'] = '<p>' . $contact_count_reply['result'] . '</p>';
  }
  return $form;
}