cmrf_views.cmrf_dataset.*:
  type: config_entity
  label: 'CiviMRF Views dataset'
  mapping:
    id:
      type: string
      label: 'Machine Name'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    connector:
      type: string
      label: 'Connector'
    entity:
      type: string
      label: 'Entity'
    action:
      type: string
      label: 'Action'
    getcount:
      type: string
      label: 'Getcount api action'
    getfields:
      type: string
      label: 'Getfields api action'
    params:
      type: string
      label: 'API Parameters'
    api_version:
      type: integer
      label: 'API version'
    relationships:
      type: sequence
      label: 'Relationships'
      sequence:
        type: mapping
        label: 'Relationship settings'
        mapping:
          id:
            type: string
          label:
            type: label
            label: 'Label'
          relationship_settings:
            type: cmrf_views.cmrf_dataset_relationship

cmrf_views.cmrf_dataset_relationship.*:
  type: config_entity
  label: 'Relationship Settings'
  mapping:
    id:
      type: string
      label: 'Machine Name'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    referenced_dataset:
      type: cmrf_views.cmrf_dataset
      label: 'Referenced Dataset'
    referenced_key:
      type: string
      label: 'Referenced Dataset Key'
    referencing_dataset:
      type: cmrf_views.cmrf_dataset
    referencing_key:
      type: string
      label: 'Referencing Dataset foreign key'

views.filter.cmrf_views_filter_optionlist:
  type: views_filter
  label: 'CiviMRF Filter list'
  mapping:
    operator:
      type: string
      label: 'Operator'
    value:
      type: sequence
      label: 'Values'
      sequence:
        type: string
        label: 'Value'
    expose:
      type: mapping
      label: 'Expose'
      mapping:
        reduce:
          type: boolean
          label: 'Reduce'
    group_info:
      mapping:
        group_items:
          sequence:
            type: views.filter.group_item.cmrf_views_filter_optionlist
            label: 'Group item'

views.relationship.cmrf_dataset_relationship:
  type: views_relationship
  label: 'CiviMRF Dataset Relationship'

views.filter_value.cmrf_views_filter_numeric:
  type: views.filter_value.numeric
  label: 'Numeric'
views.filter_value.cmrf_views_filter_date:
  type: views.filter_value.date
  label: 'Date'
