<?php

/**
 * Implements hook_rules_category_info().
 */
function cmrf_rules_rules_category_info() {
  return array(
    'civimrf' => array(
      'label' => t('CiviMRF'),
      'weight' => 0,
    ),
  );
}

/**
 * Implements hook_rules_data_info().
 */
function cmrf_rules_rules_data_info() {
  return array(
    'civimrf_call' => array(
      'label' => t('CiviMRF Call'),
    ),
  );
}

/**
 * Implements hook_rules_action_info().
 */
function cmrf_rules_rules_action_info() {
  $items = array();

  // Action for sending an API call with configurable CiviMRF profile, API
  // entity, action, parameters and options, and the CiviMRF call being provided
  // as a variable.
  $items['cmrf_send_call'] = array(
    'label' => t('Send CiviMRF call'),
    'group' => t('CiviMRF'),
    'parameter' => array(
      'cmrf_profile' => array(
        'type' => 'text',
        'label' => t('CiviMRF connection profile'),
        'options list' => 'cmrf_core_list_profile_labels',
        'restriction' => 'input',
      ),
      'cmrf_entity' => array(
        'type' => 'text',
        'label' => t('CiviCRM API entity'),
      ),
      'cmrf_action' => array(
        'type' => 'text',
        'label' => t('CiviCRM API action'),
      ),
      'cmrf_parameters' => array(
        'type' => 'text',
        'label' => t('CiviCRM API parameters'),
        'description' => t('JSON-formatted parameter list for the CiviCRM API call.'),
      ),
      'cmrf_options' => array(
        'type' => 'text',
        'label' => t('CiviCRM API options'),
        'description' => t('JSON-formatted options list for the CiviCRM API call.'),
      ),
    ),
    'provides' => array(
      'call' => array(
        'label' => t('CiviCRM API call'),
        'type' => 'civimrf_call',
        'save' => TRUE,
      ),
    ),
    'base' => 'cmrf_rules_send_call',
  );

  return $items;
}

/**
 * Register a connector for the given profile.
 *
 * @param array | NULL $profile
 *   A CiviMRF profile array structure, or NULL to use the default profile.
 *
 * @return string
 *   The ID of the connector for the given profile.
 */
function cmrf_rules_get_connector_id($profile = NULL) {
  $connector_name = 'cmrf_rules_connector';
  if (!empty($profile)) {
    $connector_name .= ':'.$profile;
  }

  $core = cmrf_core_get_core();
  $connector_id = variable_get($connector_name);
  if (empty($connector_id)) {
    $connector_id = $core->registerConnector($connector_name, $profile);
    variable_set($connector_name, $connector_id);
  }
  return $connector_id;
}

/**
 * Send a CiviCRM API call.
 *
 * @param string $profile
 *   The system name of the CiviMRF profile.
 * @param string $entity
 *   The CiviCRM API entity.
 * @param string $action
 *   The CiviCRM API action.
 * @param string $parameters
 *   A JSON-formatted representation of the CiviCRM API parameters.
 * @param string $options
 *   A JSON-formatted representation of the CiviCRM API options.
 *
 * @return array
 */
function cmrf_rules_send_call($profile, $entity, $action, $parameters, $options) {
  $parameters = json_decode($parameters, TRUE);
  $options = json_decode($options, TRUE);
  $connector_id = cmrf_rules_get_connector_id($profile);
  $core = cmrf_core_get_core();
  $call = $core->createCall($connector_id, $entity, $action, $parameters, $options);
  $core->executeCall($call);
  return array(
    'call' => $call,
  );
}

/**
 * Implements hook_rules_event_info().
 */
function cmrf_rules_rules_event_info() {
  $items = array(
    'cmrf_call_failed' => array(
      'label' => t('Call failed'),
      'group' => t('CiviMRF'),
      'variables' => array(
        'call' => array(
          'type' => 'civimrf_call',
          'label' => t('CiviMRF Call')
        )
      ),
    ),
    'cmrf_call_done' => array(
      'label' => t('Call succeeded'),
      'group' => t('CiviMRF'),
      'variables' => array(
        'call' => array(
          'type' => 'civimrf_call',
          'label' => t('CiviMRF Call')
        )
      ),
    ),
  );
  return $items;
}

/**
 * Implements hook_token_info().
 */
function cmrf_rules_token_info() {
  $info['types']['civimrf_call'] = array(
    'name' => t('CiviMRF Call'),
    'description' => t('The CiviMRF call'),
  );
  $info['tokens']['civimrf_call']['cid'] = array(
    'name' => t("Call ID"),
    'description' => t('The ID of the call record.'),
  );
  $info['tokens']['civimrf_call']['status'] = array(
    'name' => t("Status"),
    'description' => t('The status of the call.'),
  );
  $info['tokens']['civimrf_call']['profile'] = array(
    'name' => t("Profile"),
    'description' => t('The profile used to make the call.'),
  );
  $info['tokens']['civimrf_call']['request'] = array(
    'name' => t("Request"),
    'description' => t('The request data of the call.'),
  );
  $info['tokens']['civimrf_call']['reply'] = array(
    'name' => t("Reply"),
    'description' => t('The reply data of the call.'),
  );
  $info['tokens']['civimrf_call']['date'] = array(
    'name' => t("Date"),
    'description' => t('The date of the call.'),
  );
  $info['tokens']['civimrf_call']['reply_date'] = array(
    'name' => t("Reply date"),
    'description' => t('The date of the reply of the call.'),
  );
  $info['tokens']['civimrf_call']['scheduled_date'] = array(
    'name' => t("Scheduled date"),
    'description' => t('The scheduled date of of the call.'),
  );
  $info['tokens']['civimrf_call']['cached_until'] = array(
    'name' => t("Cached until"),
    'description' => t('Till when is the reply of the call cached.'),
  );
  $info['tokens']['civimrf_call']['retry_count'] = array(
    'name' => t("Retry count"),
    'description' => t('Number of retries left of the call when it fails.'),
  );
  $info['tokens']['civimrf_call']['metadata'] = array(
    'name' => t("Metadata"),
    'description' => t('The metadata of the call.'),
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function cmrf_rules_tokens($type, $tokens, array $data = [], array $options = []) {
  $replacements = array();
  if ($type == 'civimrf_call' && isset($data['civimrf_call'])) {
    $core = cmrf_core_get_core();
    $call = $data['civimrf_call'];
    foreach($tokens as $name => $original) {
      switch ($name) {
        case 'cid':
          $replacements[$original] = $call->getID();
          break;
        case 'date':
          $replacements[$original] = format_date($call->getDate()->getTimestamp());
          break;
        case 'scheduled_date':
          if (!empty($call->getScheduledDate())) {
            $replacements[$original] = format_date($call->getScheduledDate()->getTimestamp());
          } else {
            $replacements[$original] = '';
          }
          break;
        case 'reply_date':
          if (!empty($call->getReplyDate())) {
            $replacements[$original] = format_date($call->getReplyDate()->getTimestamp());
          } else {
            $replacements[$original] = '';
          }
          break;
        case 'cached_until':
          if (!empty($call->getCachedUntil())) {
            $replacements[$original] = format_date($call->getCachedUntil()->getTimestamp());
          } else {
            $replacements[$original] = '';
          }
          break;
        case 'status':
          $replacements[$original] = $call->getStatus();
          break;
        case 'profile':
          $profile = $core->getConnectionProfile($call->getConnectorID());
          $replacements[$original] = $profile['label'];
          break;
        case 'request':
          $replacements[$original] = json_encode($call->getRequest(), JSON_PRETTY_PRINT);
          break;
        case 'reply':
          $replacements[$original] = json_encode($call->getReply(), JSON_PRETTY_PRINT);
          break;
        case 'metadata':
          $replacements[$original] = json_encode($call->getMetadata(), JSON_PRETTY_PRINT);
          break;
        case 'retry_count':
          $replacements[$original] = $call->getRetryCount();
          break;
      }
    }
  }
  return $replacements;
}

function cmrf_rules_cmrf_core_call_failed(\CMRF\Core\Call $call) {
  rules_invoke_event('cmrf_call_failed', $call);
}

function cmrf_rules_cmrf_core_call_done(\CMRF\Core\Call $call) {
  rules_invoke_event('cmrf_call_done', $call);
}
